In [13]:
import pandas as pd

In [14]:
df = pd.read_excel('Копия DatafinitiElectronicsProductsPricingData.xlsx')
df.shape

(7249, 18)

In [15]:
df.head()

,id,prices.amountMax,prices.amountMin,prices.availability,prices.currency,prices.dateSeen,prices.isSale,prices.merchant,prices.shipping,brand,manufacturer,primaryCategories,weight,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,AVphzgbJLJeJML43fA0o,104.99,104.99,Yes,USD,"2017-03-30T06:00:00Z,2017-03-10T22:00:00Z,2017...",False,Bestbuy.com,NaN,Sanus,NaN,Electronics,32.8 pounds,NaN,NaN,NaN,NaN,NaN
1,AVpgMuGwLJeJML43KY_c,69,64.99,In Stock,USD,2017-12-14T06:00:00Z,True,Walmart.com,Expedited,Boytone,Boytone,Electronics,14 pounds,NaN,NaN,NaN,NaN,NaN
2,AVpgMuGwLJeJML43KY_c,69,69,In Stock,USD,2017-09-08T05:00:00Z,False,Walmart.com,Expedited,Boytone,Boytone,Electronics,14 pounds,NaN,NaN,NaN,NaN,NaN
3,AVpgMuGwLJeJML43KY_c,69.99,69.99,Yes,USD,2017-10-10T05:00:00Z,False,Bestbuy.com,NaN,Boytone,Boytone,Electronics,14 pounds,NaN,NaN,NaN,NaN,NaN
4,AVpgMuGwLJeJML43KY_c,66.99,66.99,Yes,USD,2017-08-28T07:00:00Z,False,Bestbuy.com,NaN,Boytone,Boytone,Electronics,14 pounds,NaN,NaN,NaN,NaN,NaN

In [16]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.head()

,id,prices.amountMax,prices.amountMin,prices.availability,prices.currency,prices.dateSeen,prices.isSale,prices.merchant,prices.shipping,brand,manufacturer,primaryCategories,weight
0,AVphzgbJLJeJML43fA0o,104.99,104.99,Yes,USD,"2017-03-30T06:00:00Z,2017-03-10T22:00:00Z,2017...",False,Bestbuy.com,NaN,Sanus,NaN,Electronics,32.8 pounds
1,AVpgMuGwLJeJML43KY_c,69,64.99,In Stock,USD,2017-12-14T06:00:00Z,True,Walmart.com,Expedited,Boytone,Boytone,Electronics,14 pounds
2,AVpgMuGwLJeJML43KY_c,69,69,In Stock,USD,2017-09-08T05:00:00Z,False,Walmart.com,Expedited,Boytone,Boytone,Electronics,14 pounds
3,AVpgMuGwLJeJML43KY_c,69.99,69.99,Yes,USD,2017-10-10T05:00:00Z,False,Bestbuy.com,NaN,Boytone,Boytone,Electronics,14 pounds
4,AVpgMuGwLJeJML43KY_c,66.99,66.99,Yes,USD,2017-08-28T07:00:00Z,False,Bestbuy.com,NaN,Boytone,Boytone,Electronics,14 pounds

In [18]:
df.shape

(7249, 13)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7249 entries, 0 to 7248
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   7249 non-null   str
 1   prices.amountMax     7249 non-null   object
 2   prices.amountMin     7249 non-null   object
 3   prices.availability  7249 non-null   object
 4   prices.currency      7249 non-null   str
 5   prices.dateSeen      7249 non-null   str
 6   prices.isSale        7249 non-null   bool
 7   prices.merchant      7249 non-null   str
 8   prices.shipping      4277 non-null   str
 9   brand                7249 non-null   str
 10  manufacturer         3235 non-null   object
 11  primaryCategories    7249 non-null   str
 12  weight               7249 non-null   object
dtypes: bool(1), object(5), str(7)
memory usage: 686.8+ KB

In [21]:
df['prices.currency'].value_counts()

prices.currency
USD    7248
CAD       1
Name: count, dtype: int64

In [ ]:
i